name: Build and Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v23
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build

      - name: Upload built site (dist folder)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
