name: Monthly Paper Finder

on:
  schedule:
    - cron: '0 0 6 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install paperfinder
        run: cd paperfinder && pip install -e .

      - name: Generate monthly MDX
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python paperfinder/generate.py

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/pages/monthly/*.mdx
          git commit -m "chore: update monthly papers" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: monthly-paperfinder
          title: "Add monthly papers"
          commit-message: "chore: update monthly papers"
          body: |
            Automated monthly update of recommended papers.